# coding: utf-8

"""
    全部  API 文档

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class FollowerModel(BaseModel):
    """
    FollowerModel
    """ # noqa: E501
    id: Optional[StrictInt] = None
    target_user_id: Optional[StrictInt] = Field(default=None, alias="targetUserID")
    alias: Optional[StrictStr] = None
    nick_name: Optional[StrictStr] = Field(default=None, alias="nickName")
    avatar: Optional[StrictStr] = None
    is_mutual: Optional[StrictBool] = Field(default=None, alias="isMutual")
    closeness_score: Optional[StrictInt] = Field(default=None, alias="closenessScore")
    attention_score: Optional[StrictInt] = Field(default=None, alias="attentionScore")
    tags: Optional[StrictStr] = None
    status: Optional[StrictStr] = None
    remark: Optional[StrictStr] = None
    create_date: Optional[datetime] = Field(default=None, alias="createDate")
    __properties: ClassVar[List[str]] = ["id", "targetUserID", "alias", "nickName", "avatar", "isMutual", "closenessScore", "attentionScore", "tags", "status", "remark", "createDate"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FollowerModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if alias (nullable) is None
        # and model_fields_set contains the field
        if self.alias is None and "alias" in self.model_fields_set:
            _dict['alias'] = None

        # set to None if nick_name (nullable) is None
        # and model_fields_set contains the field
        if self.nick_name is None and "nick_name" in self.model_fields_set:
            _dict['nickName'] = None

        # set to None if avatar (nullable) is None
        # and model_fields_set contains the field
        if self.avatar is None and "avatar" in self.model_fields_set:
            _dict['avatar'] = None

        # set to None if tags (nullable) is None
        # and model_fields_set contains the field
        if self.tags is None and "tags" in self.model_fields_set:
            _dict['tags'] = None

        # set to None if status (nullable) is None
        # and model_fields_set contains the field
        if self.status is None and "status" in self.model_fields_set:
            _dict['status'] = None

        # set to None if remark (nullable) is None
        # and model_fields_set contains the field
        if self.remark is None and "remark" in self.model_fields_set:
            _dict['remark'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FollowerModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "targetUserID": obj.get("targetUserID"),
            "alias": obj.get("alias"),
            "nickName": obj.get("nickName"),
            "avatar": obj.get("avatar"),
            "isMutual": obj.get("isMutual"),
            "closenessScore": obj.get("closenessScore"),
            "attentionScore": obj.get("attentionScore"),
            "tags": obj.get("tags"),
            "status": obj.get("status"),
            "remark": obj.get("remark"),
            "createDate": obj.get("createDate")
        })
        return _obj


