# coding: utf-8

"""
    全部  API 文档

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class ServiceItem(BaseModel):
    """
    ServiceItem
    """ # noqa: E501
    id: Optional[StrictInt] = None
    biz_code: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(default=None, alias="bizCode")
    provider_code: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(default=None, alias="providerCode")
    group_code: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(default=None, alias="groupCode")
    name: Optional[Annotated[str, Field(strict=True, max_length=100)]] = None
    code: Optional[Annotated[str, Field(strict=True, max_length=50)]] = None
    value_type: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(default=None, alias="valueType")
    icon: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    value_defaults: Optional[StrictStr] = Field(default=None, alias="valueDefaults")
    description: Optional[StrictStr] = None
    tags: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    is_system: Optional[StrictBool] = Field(default=None, alias="isSystem")
    show: Optional[StrictBool] = None
    show_index: Optional[StrictInt] = Field(default=None, alias="showIndex")
    create_date: Optional[datetime] = Field(default=None, alias="createDate")
    last_update: Optional[datetime] = Field(default=None, alias="lastUpdate")
    __properties: ClassVar[List[str]] = ["id", "bizCode", "providerCode", "groupCode", "name", "code", "valueType", "icon", "valueDefaults", "description", "tags", "isSystem", "show", "showIndex", "createDate", "lastUpdate"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ServiceItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if biz_code (nullable) is None
        # and model_fields_set contains the field
        if self.biz_code is None and "biz_code" in self.model_fields_set:
            _dict['bizCode'] = None

        # set to None if provider_code (nullable) is None
        # and model_fields_set contains the field
        if self.provider_code is None and "provider_code" in self.model_fields_set:
            _dict['providerCode'] = None

        # set to None if group_code (nullable) is None
        # and model_fields_set contains the field
        if self.group_code is None and "group_code" in self.model_fields_set:
            _dict['groupCode'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if code (nullable) is None
        # and model_fields_set contains the field
        if self.code is None and "code" in self.model_fields_set:
            _dict['code'] = None

        # set to None if value_type (nullable) is None
        # and model_fields_set contains the field
        if self.value_type is None and "value_type" in self.model_fields_set:
            _dict['valueType'] = None

        # set to None if icon (nullable) is None
        # and model_fields_set contains the field
        if self.icon is None and "icon" in self.model_fields_set:
            _dict['icon'] = None

        # set to None if value_defaults (nullable) is None
        # and model_fields_set contains the field
        if self.value_defaults is None and "value_defaults" in self.model_fields_set:
            _dict['valueDefaults'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if tags (nullable) is None
        # and model_fields_set contains the field
        if self.tags is None and "tags" in self.model_fields_set:
            _dict['tags'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ServiceItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "bizCode": obj.get("bizCode"),
            "providerCode": obj.get("providerCode"),
            "groupCode": obj.get("groupCode"),
            "name": obj.get("name"),
            "code": obj.get("code"),
            "valueType": obj.get("valueType"),
            "icon": obj.get("icon"),
            "valueDefaults": obj.get("valueDefaults"),
            "description": obj.get("description"),
            "tags": obj.get("tags"),
            "isSystem": obj.get("isSystem"),
            "show": obj.get("show"),
            "showIndex": obj.get("showIndex"),
            "createDate": obj.get("createDate"),
            "lastUpdate": obj.get("lastUpdate")
        })
        return _obj


